version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine-grav-amd64/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-grav-armhf/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-grav-aarch64/
    schedule:
      interval: weekly